neovim/homebrew-neovim

- Formula/neovim.rb
For old version Mac, system python would be too old for neovim. Adding `depends_on :python` in such case.
> add depends_on :python for old version Mac

- Formula/neovim.rb
Homebrew has dropped the `git export` approach. Instead,
it copies the entire source dir to build dir. So the GIT_DIR
hack becomes obsolete.
Ref: https://github.com/Homebrew/homebrew/commit/359e972d4a75182ace2557e94d1a586ae66e7ad7
> Remove GIT_DIR hack

- .travis.yml
There are post-install checks in `brew audit`.
So let's audit neovim after we installed it.
> ci: audit formula after installed it

- Formula/neovim.rb
This update was [just merged](https://github.com/neovim/neovim/commit/4fc0291c730f3c42df4692dd91b09cfd806479d7) in neovim/neovim.
This keeps the formula in sync.
msgpack and unibilium are behind here too. I'll update these too unless this is intentional.
> Update dependencies to be in sync with CMakeLists

- Formula/neovim.rb
It's an optional dependency, but should improve malloc/free performance due to it's thread-local cache for small objects.
> Use jemalloc

- README.md
Due to #39, #43, #45, #47, #48, #49.
> Readme: Add hint for `'__debug' file not found` CLT bug.

- Formula/neovim.rb
During the installation, luarocks will write cache into $HOME path.
This is against Homebrew policy and can cause download trouble in rare
situtation. So let's set $HOME to buildpath.
Also for the heads up, in the future, Homebrew will build all formulae
inside an Apple Sandbox. Writing files outside prefix like this will
end up with building error.
> set $HOME to buildpath

- Formula/neovim.rb
Homebrew will hidden the output unless passing `--verbose`.
At the same time, verbose output will be recorded into log file,
which it's good for debugging.
> Compile neovim with verbose

- Formula/neovim.rb
Since this packaging code is under the `neovim` organization, it might be used as reference. It should therefore use CMake directly and not use on the top-level Makefile, which was originally only intended as convenience function for the Neovim developers.
Also updated the caveats message, using a text adapted from the Arch Linux post-install message.
> [RFC] Use CMake directly, update caveats message.

- Formula/neovim.rb
Put splatted arguments (*std_cmake_args) last to ensure Ruby 1.8 compatibility
> Ensure Ruby 1.8 compatibility

- Formula/neovim.rb
> deps: Update to libtermkey 0.18.

- Formula/neovim.rb
Change symlinks to point from the new location of Neovim's config files. I believe [this merge](https://github.com/neovim/neovim/commit/6b4063fafe5401b95d1f35ecb7f8dfe0079b7450) changed the location of these config files. (Also see [this Reddit thread](https://www.reddit.com/r/neovim/comments/3qgsza/psa_if_neovim_stopped_loading_your_nvimrc_after/), which points to [issue #78](https://github.com/neovim/neovim/issues/78).)
> update symlink targets to point from new neovim config file locations

- Formula/neovim.rb
As per [bergman](https://github.com/bergman)'s comment on [PR #102](https://github.com/neovim/homebrew-neovim/pull/102), I've switched the order of the symlinks in the formula to be more logical.
> switch the order of the config symlinks in formula

- Formula/neovim.rb
```
== /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb ==
C:123: 72: Avoid comma after the last item of an array, unless each item is on its own line.
1 file inspected, 1 offense detected
```
I'm pretty sure at some point (11f258c766bfeecf2c2d53fbd2f11727ce40d929) the audit asked for the trailing comma to be added, I don't think I would have changed it otherwise.. oh well.
> Fix brew audit offense.

- Formula/neovim.rb
Too many folks where running into issues with stray iconv libraries on
their system, so let's just direct Neovim to use the system version
explicitly.  It's conditional to OS X to avoid causing issues with
linuxbrew users.
> Highly encourage the use of the system iconv library on OS X.

- Formula/neovim.rb
OS X 10.11.4 is now required FORTIFY_SOURCE flag.
See https://github.com/neovim/neovim/issues/4485
> Add '-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1' to cmake_args

- Formula/neovim.rb
Fixed `if OS.mac` issue and support `Release` build. and
> Thanks. Cmakelist.txt should so this automatically... Why doesn't it?
Maybe Homebrew always automatically resets `CMAKE_C_FLAGS_***=-DNDEBUG`.
Caused by this?
```bash
==> Building Neovim.
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/neovim/0.1.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DDEPS_PREFIX=../deps-build/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE='-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1' -DIconv_INCLUDE_DIRS:PATH=/usr/include -DIconv_LIBRARIES:PATH=/usr/lib/libiconv.dylib
```
NOTE:
`clang` began to display a warning from 10.10.4. Both of Homebrew and `ninja` build.
But I don't know the …
> Fix FORTIFY_SOURCE flag to OS.mac only and Support Realese build

- Formula/neovim.rb
Third party dependency luv was introduced in neovim/neovim@4ae7acd.
> Fix #143: missing third_party dependency luv

- Formula/neovim.rb
In HEAD, we now require gperf, but OS X already has it--at least since
Yosemite.  So let's turn off the building of gperf in the deps build.
> Fix #175: Neovim depends on gperf

- Formula/neovim.rb
Homebrew uses shallow clones by default. That means that the history consists
only of the latest commit and no tags.
git-describe was not amused.
Now we use a full clone instead.
Closes #135.
> Report correct version for --HEAD

- Formula/neovim.rb
Stable and head have their resources respectively, though the resources are completely same.
Both of resources have been upgraded same time according to commits or PRs, so having separated resources is nonsense at this moment.
> Unify resources for stable and them for head

- Formula/neovim.rb
This part was introduced in #138 to fix v0.1.2 bug.
Even at that time, the bug is already fixed on head (this is why `unless build.head?`).
A long time has passed, and now there is no need to handling the bug anymore.
This PR also fix the problem that RelWithDebInfo's CFLAGS is ignored.
> Remove addition of FORTIFY_SOURCE, which is not needed anymore

- Formula/neovim.rb
Neovim needs `gperf` apparently, and also neovim needs `unzip`, which is required by `luarocks`.
Both are bundled with macOS, but not with some linux distro.
> Add deps for linux

- Formula/neovim.rb
`ENV.deparallelize` was added in a0e6cb8, with no reason.
Since neovim upstream make use of parallel already and parallel build has no problem, I think we can remove this and take advantage of parallel build.
> Re-parallelize build

- Formula/neovim.rb
A Workaround for neovim/neovim#5681, until #201 is fixed.
> Use static library of jemalloc on macOS

- Formula/neovim.rb
When homebrew is installed in a non-default path (e.g. under `~`)
this formula wasn't able to find the msgpack dylib.
This change explicitly configures the build to use the msgpack dylib
from the path in which homebrew installed it.
This should fix errors encountered at install like
`error on install: dyld: Library not loaded: @rpath/libmsgpackc.2.dylib`
> Explicitly use msgpack from homebrew

- Formula/neovim.rb
The advice in the caveats doesn't match nvim's help since neovim/neovim#6505
> Remove suggested symlinks from caveats
